version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/admin
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: 'postgres:13.1-alpine'
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    volumes:
      - db:/var/lib/postgresql/data

  kong-database:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    ports:
      - 5432:5432
    networks:
      - kong-net

  kong-migration:
    image: kong/kong-gateway:3.5.0.1
    command: "kong migrations bootstrap"
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kongpass
      KONG_PASSWORD: test
    depends_on:
      - kong-database
    
  kong-gateway:
    image: kong/kong-gateway:3.5.0.1
    restart: always
    environment: 
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 8004:8004
      - 8443:8443
      - 8444:8444
      - 8445:8445
    networks:
      - kong-net
    depends_on:
      - kong-migration
volumes:
  db:

networks:
  kong-net:
      