version: '3'

services:
  # kong-database:
  #   image: postgres:13-alpine
  #   hostname: kong-database
  #   container_name: kong-database
  #   environment:
  #     POSTGRES_USER: kong
  #     POSTGRES_DB: kong
  #     POSTGRES_PASSWORD: kongpass

  # kong-migration:
  #   image: kong/kong-gateway:3.5.0.1
  #   command: "kong migrations bootstrap"
  #   environment:
  #     KONG_DATABASE: postgres
  #     KONG_PG_HOST: kong-database
  #     KONG_PG_PASSWORD: kongpass
  #     KONG_PASSWORD: test
  #   depends_on:
  #     - kong-database

  # kong-gateway:
  #   image: kong/kong-gateway:3.5.0.1
  #   restart: always
  #   environment: 
  #     KONG_DATABASE: postgres
  #     KONG_PG_HOST: kong-database
  #     KONG_PG_USER: kong
  #     KONG_PG_PASSWORD: kongpass
  #     KONG_PROXY_ACCESS_LOG: /dev/stdout
  #     KONG_ADMIN_ACCESS_LOG: /dev/stdout
  #     KONG_PROXY_ERROR_LOG: /dev/stderr
  #     KONG_ADMIN_ERROR_LOG: /dev/stderr
  #     KONG_ADMIN_LISTEN: 0.0.0.0:8001
  #     KONG_ADMIN_GUI_URL: http://localhost:8002
  #   ports:
  #     - 8000:8000
  #     - 8001:8001
  #     - 8002:8002
  #     - 8003:8003
  #     - 8004:8004
  #     - 8443:8443
  #     - 8444:8444
  #     - 8445:8445
  #   depends_on:
  #     - kong-migration

  # app:
  #     build:
  #       context: ./
  #       dockerfile: ./Dockerfile
  #     restart: on-failure
  #     environment:
  #       SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/admin
  #       SPRING_DATASOURCE_USERNAME: admin
  #       SPRING_DATASOURCE_PASSWORD: naughts&passwords
  #       SPRING_JPA_HIBERNATE_DDL_AUTO: update
  #     ports:
  #       - "8080:8080"
  #     depends_on:
  #       - db
        
  pgadmin:
      container_name: pgadmin4_container
      depends_on:
          - db
      image: dpage/pgadmin4
 
      environment:
          - PGADMIN_DEFAULT_EMAIL=admin@admin.com                           ### replace the PGADMIN-EMAIL with your desired EMAIL
          - PGADMIN_DEFAULT_PASSWORD=pass                     ### replace the PGADMIN-PASSWORD with your desired PASSWORD
      ports:
          - "5050:80"

  db:
    image: 'postgres:13.1-alpine'
    restart: always
    container_name: db
    expose: 
      - "5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: naughts&passwords
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:

# networks:
#   kong-net:

      